services:
  test_technique:
    build: .
    ports:
      - "8888:8888" # Port for Jupyter Notebook/Lab
    volumes:
      - C:\Users\antoi\Downloads\YouTubeFaces\:/dataset:ro # Path to the dataset(s)
      - .\container_output\:/output # Path to a folder to save the results of the computations
      - .:/workspace/ # Path to the repo containing the code written for this test
      - C:\Users\antoi\Downloads\facenet-models\20180402-114759:/models:ro # Path to the models
